name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Or main, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Build
        # The --public-url is important for GitHub Pages
        run: trunk build --public-url /random-karma/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # If you are deploying to a custom domain, you might want to customize the cname
          # cname: your.custom.domain.com
